import React from 'react';
import { Link } from "react-router-dom";
import SoftwareHeader from "@/pages/services/SoftwareDevelopment/SoftwareHeader";

const IotAppDevelopment: React.FC = () => {
  return (
    <>
      {/* Header */}
      <SoftwareHeader />

      <section className="py-24 bg-white">
        <div className="max-w-7xl px-6 md:px-12 lg:px-24">
          {/* Hero Section */}
          <div className="max-w-4xl mb-12 pt-6">
            <h2 className="text-3xl md:text-4xl font-bold text-[#006A7C] mb-4">
              IoT App Development Services
            </h2>
            <p className="text-lg text-gray-600">
              If your business is ready to take the next big step and have an IoT application, we are here to make it a reality for you.
            </p>
            <p className="text-lg text-gray-600 mt-2 font-medium">
              Prices start at $20/hour.
            </p>
          </div>

          {/* Intro */}
          <div className="max-w-5xl mb-16 space-y-4">
            <p className="text-gray-700 leading-relaxed">
              IoT apps are making a significant impact in these modern times. Any business that plans to transform and explore a new level of innovation can benefit from IoT app development services. With apps powered by the Internet of Things, you can connect various physical devices, enabling seamless communication. This allows your business to move towards improved data capabilities, powerful products, and intelligent designs.
            </p>
            <p className="text-gray-700 leading-relaxed">
              When you work with a professional and experienced IoT app development company like **Nimble Acuity**, we bring you a team of seasoned app developers who excel in the field of the Internet of Things. Coupled with our access to the latest resources, we are the most competent partner for your IoT app development projects, no matter the size or complexity. We offer both B2B and B2C enterprise solutions to businesses of all scales.
            </p>
          </div>

          {/* Services */}
          <div className="max-w-6xl mb-16">
            <h3 className="text-2xl font-semibold text-[#006A7C] mb-4">
              Our IoT App Development Services
            </h3>
            <p className="text-gray-700 leading-relaxed mb-6">
              Nimble Acuity is uniquely positioned to help you improve your business value using the technological breakthrough of IoT. Our services are designed to empower your business and create greater opportunities.
            </p>
            <ul className="list-disc list-inside space-y-4 text-gray-700">
              <li>
                <strong>IoT Application Development:</strong> We develop native, hybrid, web, and PWA applications for various operating systems and frameworks. We integrate AI and machine learning features to provide predictive insights and remote control capabilities for IoT devices.
              </li>
              <li>
                <strong>IoT App Development for Wearables:</strong> We can integrate your app with wearable technology, leveraging microcomputers and sensors to create accurate and precise self-tracker apps.
              </li>
              <li>
                <strong>IoT Architecture for Connected Ecosystems:</strong> We help you conceptualize and build scalable architectures that efficiently handle the massive data influx from various sources. We also integrate all your devices into a cohesive architecture for easier management.
              </li>
              <li>
                <strong>User Experience for IoT:</strong> We focus on creating a seamless and unified user experience across different IoT hardware devices and their control applications. We integrate real-time feedback systems to continuously enhance the user journey.
              </li>
              <li>
                <strong>IoT Platform Integration:</strong> Our services extend to integrating your product across various connected devices and channels, such as sensor gateways, point-of-sale systems, and social media.
              </li>
              <li>
                <strong>Testing and Maintenance:</strong> We perform preventive, adaptive, and perfective maintenance to ensure your IoT application is always performing at its full potential.
              </li>
              <li>
                <strong>Data Analytics for Smart Devices:</strong> We offer data analytics services to clean, analyze, and transform the vast amounts of data generated by your IoT ecosystem, helping you gain rich business insights and strategies.
              </li>
            </ul>
          </div>

          {/* Why Choose Us */}
          <div className="max-w-6xl mb-16">
            <h3 className="text-2xl font-semibold text-[#006A7C] mb-4">
              Why Partner with Nimble Acuity?
            </h3>
            <p className="text-gray-700 leading-relaxed mb-4">
              Nimble Acuity is a leading IoT app development service provider. With our team of skilled developers and engineers, we are your one-stop solution for all your IoT application needs.
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700">
              <li>
                <strong>Highly Affordable Services:</strong> We make it easy for businesses of all sizes to collaborate with us, as our services are highly cost-effective and don't come with up-front charges.
              </li>
              <li>
                <strong>ISO-Certified:</strong> As an ISO 9001:2015 certified company, we ensure the quality of our services and team.
              </li>
              <li>
                <strong>Data Security:</strong> We have stringent data security measures in place to ensure all your information remains completely safe.
              </li>
              <li>
                <strong>Quick Turnaround:</strong> Our team is fully equipped with the skills and resources to provide services with quick turnaround times.
              </li>
              <li>
                <strong>Scalability:</strong> We are prepared with a capable team and resources to accommodate your upscaling requirements as your business grows.
              </li>
              <li>
                <strong>24/7 Support:</strong> Our customer care executives are available around the clock to resolve your queries and provide timely updates.
              </li>
            </ul>
          </div>

          {/* CTA */}
          <div className="max-w-4xl mt-16">
            <h3 className="text-2xl font-bold text-[#006A7C] mb-4">
              Ready to Innovate with IoT?
            </h3>
            <p className="text-gray-700 mb-6">
              With over 26 years of industry experience, we offer a range of services including big data management and predictive analysis. With our global delivery centers, we assure you of high-quality services with 100% transparency.
            </p>
            <p className="text-gray-700 mb-8 font-medium">
              If you're looking for quality IoT app development services at affordable rates, get in touch with us today.
            </p>
            <Link to="/contact">
              <button className="bg-[#006A7C] text-white px-8 py-3 rounded-xl shadow hover:bg-[#005662] transition font-medium">
                Get in Touch Today
              </button>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
};

export default IotAppDevelopment;