import React from 'react';
import { Link } from "react-router-dom";
import SoftwareHeader from "@/pages/services/SoftwareDevelopment/SoftwareHeader";

const IoTAnalyticsDevelopment: React.FC = () => {
  return (
    <>
      {/* Header */}
      <SoftwareHeader />

      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-6 md:px-12 lg:px-24">

          {/* Hero Section */}
          <div className="max-w-4xl mb-12 pt-6">
            <h2 className="text-3xl md:text-4xl font-bold text-[#006A7C] mb-4">
              IoT Analytics Development Services
            </h2>
            <p className="text-lg text-gray-600">
              Increase your business value with powerful Big Data Analytics and AI-driven insights for your IoT ecosystem.
            </p>
          </div>

          {/* Intro */}
          <div className="max-w-5xl mb-16 space-y-4">
            <p className="text-gray-700 leading-relaxed">
              IoT analytics applications are essential tools for extracting value from the vast amounts of data generated by connected devices. These applications help you generate insights, discover patterns, and create predictions that are crucial for making informed business decisions. At **Nimble Acuity**, we offer a fully managed IoT analytics service that automatically scales to support petabytes of data, ensuring you never miss a valuable insight.
            </p>
            <p className="text-gray-700 leading-relaxed">
              We are a leading IoT analytics development company capable of handling any project, from a handful of sensors for a warehouse to an entire IoT architecture for a major enterprise. Our services are built with an emphasis on consistency, reliability, and agility to meet your business needs.
            </p>
          </div>

          {/* Our Services */}
          <div className="max-w-6xl mb-16">
            <h3 className="text-2xl font-semibold text-[#006A7C] mb-4">
              Our IoT Analytics Development Solutions
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 text-gray-700">
              <div className="space-y-2">
                <h4 className="text-xl font-bold text-[#006A7C]">IoT Software Development</h4>
                <p>Tell us your IoT software project ideas, and we'll handle every step, from initial concept to full-scale development, covering everything from sensors to entire architectures.</p>
              </div>
              <div className="space-y-2">
                <h4 className="text-xl font-bold text-[#006A7C]">Custom Cloud Solutions</h4>
                <p>We help you refactor legacy IoT applications or seamlessly migrate them to modern, cloud-based environments to enhance performance and scalability.</p>
              </div>
              <div className="space-y-2">
                <h4 className="text-xl font-bold text-[#006A7C]">Embedded IoT Software</h4>
                <p>We make it easy to launch IoT-based solutions like home automation, smart wearables, and other embedded products with our expert software development services.</p>
              </div>
              <div className="space-y-2">
                <h4 className="text-xl font-bold text-[#006A7C]">IoT Data Analytics</h4>
                <p>We empower your IoT solutions with advanced analytics capabilities, using artificial intelligence and big data to generate enhanced insights and predictions.</p>
              </div>
              <div className="space-y-2">
                <h4 className="text-xl font-bold text-[#006A7C]">IoT Mobile Applications</h4>
                <p>We develop mobile apps that monitor device interactions for a better user experience, gather behavior statistics, and provide personalized recommendations.</p>
              </div>
              <div className="space-y-2">
                <h4 className="text-xl font-bold text-[#006A7C]">IoT Consulting</h4>
                <p>We help you create products that have a strong market need and a robust technology stack, providing expert guidance from strategy to implementation.</p>
              </div>
            </div>
          </div>

          {/* Why Choose Nimble Acuity */}
          <div className="max-w-6xl mb-16">
            <h3 className="text-2xl font-semibold text-[#006A7C] mb-4">
              Why Partner with Nimble Acuity?
            </h3>
            <ul className="list-disc list-inside space-y-2 text-gray-700">
              <li><strong>Affordable & Transparent Pricing:</strong> We offer fair and transparent pricing for our services, ensuring you receive exceptional value without hidden costs.</li>
              <li><strong>High-Quality Solutions:</strong> As an ISO-certified company, our application development solutions adhere to the best international practices and workflows.</li>
              <li><strong>100% Information Security:</strong> We are committed to delivering our services in compliance with the strictest international data security regulations, protecting your data at all times.</li>
            </ul>
          </div>

          {/* CTA */}
          <div className="max-w-4xl mt-16">
            <h3 className="text-2xl font-bold text-[#006A7C] mb-4">
              Ready to Power Your Business with IoT?
            </h3>
            <p className="text-gray-700 mb-6">
              Successful IoT projects require tight coordination and cooperation between many different parties. Nimble Acuity has the specialized expertise in hardware design, microprocessor programming, wireless networking, data analytics, and security to make your IoT project a success. Let us help you create a connected experience that enables your operations, assets, and services to work effectively as one.
            </p>
            <Link to="/contact">
              <button className="bg-[#006A7C] text-white px-8 py-3 rounded-xl shadow hover:bg-[#005662] transition font-medium">
                Get a Free Quote
              </button>
            </Link>
          </div>

        </div>
      </section>
    </>
  );
};

export default IoTAnalyticsDevelopment;