import { useState } from "react";
import { Link } from "react-router-dom";
import { ChevronDown } from "lucide-react";

// The data from your document has been structured here
const serviceCategories = [
  {
    name: "Finance, Accounting & FinOps",
    path: "/services/finance",
    sub: [
      { name: "Bookkeeping & general ledger", path: "/services/finance/bookkeeping" },
      { name: "Accounts payable processing", path: "/services/finance/accounts-payable" },
      { name: "Accounts receivable & collections", path: "/services/finance/accounts-receivable" },
      { name: "Payroll processing", path: "/services/finance/payroll" },
      { name: "Payroll tax filings", path: "/services/finance/payroll-tax" },
      { name: "Sales & use tax compliance", path: "/services/finance/sales-tax" },
      { name: "Income tax preparation", path: "/services/finance/income-tax-prep" },
      { name: "Tax planning advisory", path: "/services/finance/tax-planning" },
      { name: "Fractional/Virtual CFO (FP&A)", path: "/services/finance/cfo" },
      { name: "Budgeting & forecasting", path: "/services/finance/budgeting" },
      { name: "Financial modeling", path: "/services/finance/financial-modeling" },
      { name: "Management reporting (MIS)", path: "/services/finance/management-reporting" },
      { name: "Cost accounting & standard costing", path: "/services/finance/cost-accounting" },
      { name: "Inventory accounting & reconciliation", path: "/services/finance/inventory-accounting" },
      { name: "Fixed assets & depreciation schedules", path: "/services/finance/fixed-assets" },
      { name: "Bank & cash reconciliation", path: "/services/finance/bank-reconciliation" },
      { name: "Treasury & cash management", path: "/services/finance/treasury" },
      { name: "Credit risk assessment", path: "/services/finance/credit-risk" },
      { name: "Vendor master data management", path: "/services/finance/vendor-data" },
      { name: "Customer billing & invoicing", path: "/services/finance/billing" },
      { name: "Revenue recognition (ASC 606) support", path: "/services/finance/revenue-recognition" },
      { name: "Audit preparation & support", path: "/services/finance/audit-prep" },
      { name: "Internal audit & SOX testing", path: "/services/finance/internal-audit" },
      { name: "1099/1096 compliance", path: "/services/finance/1099-compliance" },
      { name: "Grants & fund accounting (nonprofits)", path: "/services/finance/grants-accounting" },
      { name: "Expense management & policy enforcement", path: "/services/finance/expense-management" },
      { name: "Procure-to-Pay process design", path: "/services/finance/p2p" },
      { name: "Order-to-Cash process design", path: "/services/finance/o2c" },
      { name: "ERP finance implementation (NetSuite/SAP/Oracle)", path: "/services/finance/erp-implementation" },
      { name: "Finance shared services (SSC) setup", path: "/services/finance/ssc-setup" },
    ],
  },
  {
    name: "Legal, Corporate & Compliance",
    path: "/services/legal",
    sub: [
      { name: "Legal research & memoranda", path: "/services/legal/research" },
      { name: "Contract drafting (NDAs/MSAs/SOWs)", path: "/services/legal/contract-drafting" },
      { name: "Contract review & redlining", path: "/services/legal/contract-review" },
      { name: "Corporate governance & board minutes", path: "/services/legal/governance" },
      { name: "Entity formation & registration", path: "/services/legal/entity-formation" },
      { name: "Registered agent coordination", path: "/services/legal/registered-agent" },
      { name: "Annual report / Statement of Information filings", path: "/services/legal/annual-report" },
      { name: "Compliance calendars & reminders", path: "/services/legal/compliance-calendars" },
      { name: "Policy drafting (privacy, security, HR)", path: "/services/legal/policy-drafting" },
      { name: "Employment docs (handbooks/offers) support", path: "/services/legal/employment-docs" },
      { name: "IP search & docketing support", path: "/services/legal/ip-search" },
      { name: "Trademark filing assistance*", path: "/services/legal/trademark-filing" },
      { name: "Litigation support & e-discovery processing", path: "/services/legal/litigation-support" },
      { name: "Document review & coding", path: "/services/legal/document-review" },
      { name: "Subpoena/records response coordination", path: "/services/legal/subpoena-response" },
      { name: "HIPAA/PCI/GDPR/CCPA compliance programs", path: "/services/legal/compliance-programs" },
      { name: "Risk & compliance training content", path: "/services/legal/compliance-training" },
      { name: "Regulatory license tracking", path: "/services/legal/license-tracking" },
      { name: "Contract lifecycle management (CLM) admin", path: "/services/legal/clm-admin" },
      { name: "Vendor due-diligence questionnaires", path: "/services/legal/vendor-diligence" },
      { name: "Data processing agreements management", path: "/services/legal/dpa-management" },
      { name: "Immigration petition document assembly", path: "/services/legal/immigration-docs" },
      { name: "Lease abstraction & review support", path: "/services/legal/lease-abstraction" },
      { name: "Corporate secretarial services", path: "/services/legal/corporate-secretary" },
      { name: "Cap table & ESOP admin support", path: "/services/legal/cap-table-admin" },
      { name: "Notary scheduling coordination", path: "/services/legal/notary-scheduling" },
      { name: "Ethics & hotline intake triage", path: "/services/legal/ethics-triage" },
      { name: "Legal billing & matter management", path: "/services/legal/legal-billing" },
      { name: "Government filings & permits assistance", path: "/services/legal/government-filings" },
      { name: "Whistleblower & investigation support", path: "/services/legal/whistleblower-support" },
    ],
  },
  {
    name: "Healthcare & MedTech Support",
    path: "/services/healthcare",
    sub: [
      { name: "Medical billing & claims submission", path: "/services/healthcare/medical-billing" },
      { name: "CPT/ICD-10 coding", path: "/services/healthcare/coding" },
      { name: "Charge capture audits", path: "/services/healthcare/charge-capture" },
      { name: "Denial management & appeals", path: "/services/healthcare/denial-management" },
      { name: "Eligibility & benefits verification", path: "/services/healthcare/benefits-verification" },
      { name: "Prior authorization coordination", path: "/services/healthcare/prior-auth" },
      { name: "Payment posting & reconciliation", path: "/services/healthcare/payment-posting" },
      { name: "Provider credentialing & enrollment", path: "/services/healthcare/credentialing" },
      { name: "Scheduling & RCM coordination", path: "/services/healthcare/scheduling" },
      { name: "Medical transcription & scribing", path: "/services/healthcare/transcription" },
      { name: "Clinical documentation improvement (CDI) support", path: "/services/healthcare/cdi" },
      { name: "Telehealth support desk", path: "/services/healthcare/telehealth-support" },
      { name: "Patient intake & call center", path: "/services/healthcare/patient-intake" },
      { name: "Medical records release (ROI)", path: "/services/healthcare/records-release" },
      { name: "HIPAA training & audits", path: "/services/healthcare/hipaa-training" },
      { name: "DME billing support", path: "/services/healthcare/dme-billing" },
      { name: "Dental billing support", path: "/services/healthcare/dental-billing" },
      { name: "Behavioral health billing support", path: "/services/healthcare/behavioral-health-billing" },
      { name: "Revenue integrity audits", path: "/services/healthcare/revenue-audits" },
      { name: "MIPS/MACRA quality reporting support", path: "/services/healthcare/mips-reporting" },
      { name: "Healthcare analytics & dashboards", path: "/services/healthcare/analytics" },
      { name: "Population health data management", path: "/services/healthcare/population-health" },
      { name: "HIE integration support", path: "/services/healthcare/hie-integration" },
      { name: "EHR implementation/admin (Epic/Cerner/etc.)", path: "/services/healthcare/ehr-implementation" },
      { name: "HL7/LIS interfacing support", path: "/services/healthcare/hl7-support" },
      { name: "Clinical trial data coordination", path: "/services/healthcare/clinical-trial-data" },
      { name: "Device complaint handling & vigilance", path: "/services/healthcare/device-complaint" },
      { name: "Healthcare marketing compliance review", path: "/services/healthcare/marketing-compliance" },
      { name: "Coding education & provider training", path: "/services/healthcare/coding-education" },
      { name: "Physician liaison & referral management", path: "/services/healthcare/physician-liaison" },
    ],
  },
  {
    name: "IT, Software, Cloud & Cybersecurity",
    path: "/services/it",
    sub: [
      { name: "IT helpdesk & desktop support", path: "/services/it/helpdesk" },
      { name: "Managed services (MSP) & monitoring", path: "/services/it/managed-services" },
      { name: "Network design & administration", path: "/services/it/network-admin" },
      { name: "VoIP/PBX setup & management", path: "/services/it/voip" },
      { name: "Cloud migration (AWS/Azure/GCP)", path: "/services/it/cloud-migration" },
      { name: "Infrastructure-as-Code (Terraform)", path: "/services/it/iac" },
      { name: "CI/CD pipeline setup", path: "/services/it/ci-cd" },
      { name: "SRE & reliability engineering", path: "/services/it/sre" },
      { name: "Web/mobile application development", path: "/services/it/app-dev" },
      { name: "API development & integration", path: "/services/it/api-dev" },
      { name: "Microservices architecture consulting", path: "/services/it/microservices" },
      { name: "Database administration (SQL/NoSQL)", path: "/services/it/db-admin" },
      { name: "Data warehouse & ETL/ELT pipelines", path: "/services/it/data-warehouse" },
      { name: "Backup & disaster recovery", path: "/services/it/dr" },
      { name: "Identity & access management (SSO/MFA)", path: "/services/it/iam" },
      { name: "Pen-testing & vulnerability assessments", path: "/services/it/pen-testing" },
      { name: "SOC monitoring & incident response", path: "/services/it/soc-monitoring" },
      { name: "Endpoint protection & EDR management", path: "/services/it/endpoint-protection" },
      { name: "Patch management & hardening", path: "/services/it/patch-management" },
      { name: "MDM & endpoint lifecycle", path: "/services/it/mdm" },
      { name: "IT asset management & CMDB", path: "/services/it/it-asset-management" },
      { name: "IT policy & SOP documentation", path: "/services/it/it-policy-sop" },
      { name: "Software licensing management", path: "/services/it/licensing" },
      { name: "QA automation & test management", path: "/services/it/qa-automation" },
      { name: "UX/UI design & prototyping", path: "/services/it/ux-ui" },
      { name: "Robotic process automation (RPA)", path: "/services/it/rpa" },
      { name: "Low-code / no-code solutions", path: "/services/it/low-code" },
      { name: "IoT device integration", path: "/services/it/iot" },
      { name: "Blockchain solution prototyping", path: "/services/it/blockchain" },
      { name: "SOC 2 / ISO 27001 readiness & audits", path: "/services/it/soc2-iso" },
    ],
  },
  {
    name: "Data, AI, Analytics & Research",
    path: "/services/data",
    sub: [
      { name: "Data engineering & ingestion", path: "/services/data/engineering" },
      { name: "Data modeling & schema design", path: "/services/data/modeling" },
      { name: "BI dashboards & reporting", path: "/services/data/bi" },
      { name: "KPI design & data governance", path: "/services/data/kpi-governance" },
      { name: "Data quality & master data management", path: "/services/data/data-quality" },
      { name: "Statistical analysis & A/B testing", path: "/services/data/statistical-analysis" },
      { name: "Forecasting & time-series modeling", path: "/services/data/forecasting" },
      { name: "Machine learning model development", path: "/services/data/ml-dev" },
      { name: "Natural language processing (NLP)", path: "/services/data/nlp" },
      { name: "Computer vision prototyping", path: "/services/data/computer-vision" },
      { name: "Recommender systems", path: "/services/data/recommender-systems" },
      { name: "ML Ops & model monitoring", path: "/services/data/ml-ops" },
      { name: "Data labeling & annotation", path: "/services/data/data-labeling" },
      { name: "Survey design & research ops", path: "/services/data/survey-design" },
      { name: "Market research & competitive intel", path: "/services/data/market-research" },
      { name: "Compliant web data collection", path: "/services/data/web-data-collection" },
      { name: "Pricing analytics", path: "/services/data/pricing-analytics" },
      { name: "Churn & retention analytics", path: "/services/data/churn-analytics" },
      { name: "Credit scoring & risk models", path: "/services/data/credit-scoring" },
      { name: "Fraud detection & anomaly detection", path: "/services/data/fraud-detection" },
      { name: "Geospatial analytics & mapping", path: "/services/data/geospatial" },
      { name: "Experiment design & causal inference", path: "/services/data/experiment-design" },
      { name: "Data privacy & anonymization", path: "/services/data/data-privacy" },
      { name: "Synthetic data generation", path: "/services/data/synthetic-data" },
      { name: "Data catalog & lineage", path: "/services/data/data-catalog" },
      { name: "Report automation & scheduling", path: "/services/data/report-automation" },
      { name: "Excel/Sheets macro automation", path: "/services/data/excel-automation" },
      { name: "Voice-of-customer text mining", path: "/services/data/voc-mining" },
      { name: "Social listening & sentiment analysis", path: "/services/data/social-listening" },
      { name: "AI tool/vendor evaluation", path: "/services/data/ai-evaluation" },
    ],
  },
  {
    name: "Insurance BPO Services",
    path: "/services/marketing",
    sub: [
      { name: "Brand strategy & positioning", path: "/services/marketing/brand-strategy" },
      { name: "Visual identity & logo systems", path: "/services/marketing/visual-identity" },
      { name: "Graphic design & collateral", path: "/services/marketing/graphic-design" },
      { name: "Copywriting & content marketing", path: "/services/marketing/copywriting" },
      { name: "Social media management", path: "/services/marketing/social-media" },
      { name: "Influencer marketing", path: "/services/marketing/influencer" },
      { name: "SEO audits & optimization", path: "/services/marketing/seo" },
      { name: "SEM/PPC campaign management", path: "/services/marketing/sem-ppc" },
      { name: "App Store Optimization (ASO)", path: "/services/marketing/aso" },
      { name: "Email marketing & CRM journeys", path: "/services/marketing/email-marketing" },
      { name: "Marketing automation (HubSpot/Marketo)", path: "/services/marketing/marketing-automation" },
      { name: "CRO: landing pages & funnels", path: "/services/marketing/cro" },
      { name: "Video production & editing", path: "/services/marketing/video-production" },
      { name: "Photography & product shoots", path: "/services/marketing/photography" },
      { name: "Podcast production", path: "/services/marketing/podcast-production" },
      { name: "PR & media relations", path: "/services/marketing/pr" },
      { name: "Event marketing & trade shows", path: "/services/marketing/event-marketing" },
      { name: "Webinar production & moderation", path: "/services/marketing/webinar-production" },
      { name: "Affiliate & partner marketing", path: "/services/marketing/affiliate-marketing" },
      { name: "Community management", path: "/services/marketing/community-management" },
      { name: "Sales enablement materials", path: "/services/marketing/sales-enablement" },
      { name: "SDR/inside sales & appointment setting", path: "/services/marketing/sdr-sales" },
      { name: "Account-based marketing (ABM)", path: "/services/marketing/abm" },
      { name: "Lead scoring & routing", path: "/services/marketing/lead-scoring" },
      { name: "Proposal writing & RFP responses", path: "/services/marketing/proposal-writing" },
      { name: "DTC e-commerce growth marketing", path: "/services/marketing/dtc-marketing" },
      { name: "Marketplace (Amazon/Etsy/eBay) ops", path: "/services/marketing/marketplace-ops" },
      { name: "Reputation management & reviews", path: "/services/marketing/reputation-management" },
      { name: "Analytics & multi-touch attribution", path: "/services/marketing/analytics" },
      { name: "CAN-SPAM/CCPA marketing compliance", path: "/services/marketing/compliance" },
    ],
  },
  {
    name: "Customer Experience, Communications & Telephony",
    path: "/services/customer-experience",
    sub: [
      { name: "Inbound customer support", path: "/services/customer-experience/inbound-support" },
      { name: "Outbound campaigns & cold calling", path: "/services/customer-experience/outbound-campaigns" },
      { name: "Technical support (Tier 1–3)", path: "/services/customer-experience/tech-support" },
      { name: "Ticket triage & helpdesk", path: "/services/customer-experience/ticket-triage" },
      { name: "Omnichannel contact center setup", path: "/services/customer-experience/contact-center-setup" },
      { name: "IVR design & tuning", path: "/services/customer-experience/ivr-design" },
      { name: "QA & call scoring", path: "/services/customer-experience/qa-call-scoring" },
      { name: "Workforce management (WFM) scheduling", path: "/services/customer-experience/wfm" },
      { name: "Knowledge base authoring", path: "/services/customer-experience/knowledge-base" },
      { name: "Chatbot design & training", path: "/services/customer-experience/chatbot" },
      { name: "Email support & SLA management", path: "/services/customer-experience/email-support" },
      { name: "Social care & moderation", path: "/services/customer-experience/social-care" },
      { name: "NPS/CSAT program management", path: "/services/customer-experience/nps-csat" },
      { name: "Complaint resolution & escalation", path: "/services/customer-experience/complaint-resolution" },
      { name: "Customer onboarding & success playbooks", path: "/services/customer-experience/onboarding" },
      { name: "Renewals & upsell motions", path: "/services/customer-experience/renewals-upsell" },
      { name: "Early-stage collections calling", path: "/services/customer-experience/collections-calling" },
      { name: "Telecom expense management", path: "/services/customer-experience/telecom-expense" },
      { name: "SIP trunking & SBC management", path: "/services/customer-experience/sip-trunking" },
      { name: "Number provisioning & porting", path: "/services/customer-experience/number-provisioning" },
      { name: "E-fax & voicemail services", path: "/services/customer-experience/e-fax" },
      { name: "Contact center analytics", path: "/services/customer-experience/contact-center-analytics" },
      { name: "Speech analytics & QA automation", path: "/services/customer-experience/speech-analytics" },
      { name: "Remote KYC/video verification", path: "/services/customer-experience/kyc-verification" },
      { name: "Field service dispatch", path: "/services/customer-experience/field-service" },
      { name: "Emergency hotline management", path: "/services/customer-experience/hotline" },
      { name: "Accessibility services (TTY/CART)", path: "/services/customer-experience/accessibility" },
      { name: "Conference & webinar support", path: "/services/customer-experience/webinar-support" },
      { name: "Live translation/interpretation", path: "/services/customer-experience/translation" },
      { name: "DR communications planning", path: "/services/customer-experience/dr-communications" },
    ],
  },
  {
    name: "Operations, Procurement, Supply Chain & Manufacturing Support",
    path: "/services/operations",
    sub: [
      { name: "Demand planning & forecasting", path: "/services/operations/demand-planning" },
      { name: "S&OP facilitation", path: "/services/operations/s&op" },
      { name: "Strategic sourcing & RFx", path: "/services/operations/strategic-sourcing" },
      { name: "Supplier qualification & audits", path: "/services/operations/supplier-audits" },
      { name: "Purchase order management", path: "/services/operations/po-management" },
      { name: "Inventory control & cycle counts", path: "/services/operations/inventory-control" },
      { name: "Warehouse setup & optimization", path: "/services/operations/warehouse-optimization" },
      { name: "3PL selection & management", path: "/services/operations/3pl-management" },
      { name: "Transportation planning", path: "/services/operations/transportation" },
      { name: "Route optimization & last-mile", path: "/services/operations/route-optimization" },
      { name: "Import/export documentation", path: "/services/operations/import-export-docs" },
      { name: "Customs brokerage coordination", path: "/services/operations/customs-brokerage" },
      { name: "Quality management system (QMS) setup", path: "/services/operations/qms-setup" },
      { name: "Lean/Six Sigma process improvement", path: "/services/operations/lean-six-sigma" },
      { name: "SOP drafting & training", path: "/services/operations/sop-drafting" },
      { name: "Production scheduling support", path: "/services/operations/production-scheduling" },
      { name: "Maintenance planning (CMMS)", path: "/services/operations/maintenance-planning" },
      { name: "Packaging design & compliance (Prop 65)", path: "/services/operations/packaging-compliance" },
      { name: "Product lifecycle management admin", path: "/services/operations/plm-admin" },
      { name: "Spare-parts planning", path: "/services/operations/spare-parts" },
      { name: "Reverse logistics & returns", path: "/services/operations/reverse-logistics" },
      { name: "Vendor-managed inventory (VMI)", path: "/services/operations/vmi" },
      { name: "Asset tracking & RFID", path: "/services/operations/asset-tracking" },
      { name: "OSHA compliance support", path: "/services/operations/osha-compliance" },
      { name: "Food safety (HACCP) program support", path: "/services/operations/haccp" },
      { name: "Cold-chain monitoring", path: "/services/operations/cold-chain" },
      { name: "Sustainable sourcing & circularity", path: "/services/operations/sustainable-sourcing" },
      { name: "Utility bill audit & recovery", path: "/services/operations/utility-audit" },
      { name: "Business continuity planning", path: "/services/operations/bcp" },
      { name: "Operations analytics dashboards", path: "/services/operations/analytics" },
    ],
  },
  {
    name: "Real Estate, Facilities, Energy & Environment",
    path: "/services/real-estate",
    sub: [
      { name: "Brokerage support & comps research", path: "/services/real-estate/brokerage" },
      { name: "Lease abstraction & administration", path: "/services/real-estate/lease-admin" },
      { name: "Site selection & market studies", path: "/services/real-estate/site-selection" },
      { name: "Zoning & permit research", path: "/services/real-estate/zoning-research" },
      { name: "Space planning & CAD drafting", path: "/services/real-estate/space-planning" },
      { name: "Fit-out / project management", path: "/services/real-estate/fit-out-management" },
      { name: "Facilities maintenance (hard/soft)", path: "/services/real-estate/facilities-maintenance" },
      { name: "Janitorial & hygiene services", path: "/services/real-estate/janitorial" },
      { name: "Security guarding & patrol", path: "/services/real-estate/security-patrol" },
      { name: "CCTV/access control monitoring", path: "/services/real-estate/cctv-monitoring" },
      { name: "HVAC maintenance & commissioning", path: "/services/real-estate/hvac-maintenance" },
      { name: "Building automation admin (BAS)", path: "/services/real-estate/bas-admin" },
      { name: "Energy audits & benchmarking", path: "/services/real-estate/energy-audits" },
      { name: "Solar PV O&M", path: "/services/real-estate/solar-pv" },
      { name: "EV charging station operations", path: "/services/real-estate/ev-charging" },
      { name: "Utility data management & ENERGY STAR", path: "/services/real-estate/utility-data" },
      { name: "Waste management & recycling", path: "/services/real-estate/waste-management" },
      { name: "Landscape & groundskeeping", path: "/services/real-estate/landscaping" },
      { name: "Snow/ice removal (where relevant)", path: "/services/real-estate/snow-removal" },
      { name: "Fire/life-safety inspections", path: "/services/real-estate/fire-safety" },
      { name: "Environmental consulting & CEQA support", path: "/services/real-estate/environmental-consulting" },
      { name: "Air/water quality testing", path: "/services/real-estate/air-water-testing" },
      { name: "HazMat handling coordination", path: "/services/real-estate/hazmat-handling" },
      { name: "ESG strategy & reporting", path: "/services/real-estate/esg-reporting" },
      { name: "Real-estate valuation support", path: "/services/real-estate/valuation-support" },
      { name: "Title & escrow coordination", path: "/services/real-estate/title-escrow" },
      { name: "Property management & HOA support", path: "/services/real-estate/property-management" },
      { name: "Tenant communications & portals", path: "/services/real-estate/tenant-communications" },
      { name: "Move-in/out coordination", path: "/services/real-estate/move-in-out" },
      { name: "Disaster restoration services", path: "/services/real-estate/disaster-restoration" },
    ],
  },
  {
    name: "HR, Training, Admin & Specialized Professional Services",
    path: "/services/hr",
    sub: [
      { name: "Talent sourcing & recruiting", path: "/services/hr/talent-sourcing" },
      { name: "Executive search", path: "/services/hr/executive-search" },
      { name: "Background checks & verification", path: "/services/hr/background-checks" },
      { name: "Onboarding & orientation", path: "/services/hr/onboarding" },
      { name: "HR policy & handbook development", path: "/services/hr/policy-development" },
      { name: "Compensation & benefits benchmarking", path: "/services/hr/benefits-benchmarking" },
      { name: "Time & attendance systems admin", path: "/services/hr/time-attendance" },
      { name: "Employee relations case management", path: "/services/hr/employee-relations" },
      { name: "Performance management process", path: "/services/hr/performance-management" },
      { name: "LMS setup & course authoring", path: "/services/hr/lms-setup" },
      { name: "Corporate training & workshops", path: "/services/hr/corporate-training" },
      { name: "DEI program facilitation", path: "/services/hr/dei-program" },
      { name: "Multi-state payroll setup & compliance", path: "/services/hr/multi-state-payroll" },
      { name: "Visa/immigration & relocation coordination", path: "/services/hr/visa-relocation" },
      { name: "Travel management & expense audits", path: "/services/hr/travel-management" },
      { name: "Office administration & reception", path: "/services/hr/office-admin" },
      { name: "Document management & e-filing", path: "/services/hr/document-management" },
      { name: "Meeting & calendar management", path: "/services/hr/meeting-calendar" },
      { name: "Executive assistance & board support", path: "/services/hr/executive-support" },
      { name: "P-card programs & spend control", path: "/services/hr/p-card-programs" },
      { name: "Insurance broking coordination", path: "/services/hr/insurance-broking" },
      { name: "Business insurance claims support", path: "/services/hr/insurance-claims" },
      { name: "Grant writing & management", path: "/services/hr/grant-writing" },
      { name: "Fundraising & donor relations", path: "/services/hr/fundraising" },
      { name: "Nonprofit charity filings & registry", path: "/services/hr/nonprofit-filings" },
      { name: "Community outreach & CSR programs", path: "/services/hr/community-outreach" },
      { name: "Strategy & management consulting", path: "/services/hr/management-consulting" },
      { name: "Change management & org design", path: "/services/hr/change-management" },
      { name: "QA & ISO certification consulting", path: "/services/hr/qa-iso-consulting" },
      { name: "Professional coaching & mentoring", path: "/services/hr/coaching-mentoring" },
    ],
  },
  {
    name: "Global Outsourcing / Offshoring Program Management",
    path: "/services/outsourcing",
    sub: [
      { name: "Strategy & Readiness", path: "/services/outsourcing/strategy-readiness" },
      { name: "Location & Vendor Strategy", path: "/services/outsourcing/vendor-strategy" },
      { name: "Commercials & Contracting", path: "/services/outsourcing/contracting" },
      { name: "Legal, Regulatory & Compliance", path: "/services/outsourcing/compliance" },
      { name: "Transition & Knowledge Transfer (KT)", path: "/services/outsourcing/transition" },
      { name: "Operating Model & Delivery Setup", path: "/services/outsourcing/delivery-setup" },
      { name: "Technology, Integration & Security", path: "/services/outsourcing/tech-security" },
      { name: "Service Management & Performance", path: "/services/outsourcing/performance" },
      { name: "People, Culture & Change", path: "/services/outsourcing/culture-change" },
      { name: "Governance, Risk, BCP/DR & Lifecycle", path: "/services/outsourcing/governance-risk" },
    ],
  },
];

const ServicesHeader = () => {
  const [openDropdown, setOpenDropdown] = useState<string | null>(null);

  return (
    <header className="bg-[#f0faff] border-b border-[#00aaff] shadow-md py-6">
      <div className="max-w-7xl mx-auto px-6">
        <h1 className="text-2xl font-bold text-[#0077b6] mb-6 text-center">
          Our Services
        </h1>

        <div className="grid grid-cols-4 gap-6">
          {serviceCategories.map((cat) => (
            <div
              key={cat.name}
              className="relative"
              onMouseEnter={() => setOpenDropdown(cat.name)}
              onMouseLeave={() => setOpenDropdown(null)}
            >
              <Link
                to={cat.path}
                className="block p-6 bg-white rounded-lg shadow hover:bg-[#e0f7ff] hover:shadow-lg text-center text-[#0077b6] font-semibold transition-all"
              >
                {cat.name}
              </Link>

              {/* Dropdown */}
              {openDropdown === cat.name && cat.sub?.length > 0 && (
                <div className="absolute top-full left-1/2 transform -translate-x-1/2 mt-2 w-72 bg-white border border-[#00aaff] rounded-xl shadow-xl z-50 p-4">
                  <ul className="flex flex-col gap-2">
                    {cat.sub.map((sub) => (
                      <li key={sub.path}>
                        <Link
                          to={sub.path}
                          className="block px-3 py-2 text-gray-700 text-sm hover:bg-[#e0f7ff] hover:text-[#0077b6] rounded transition-colors"
                        >
                          {sub.name}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </header>
  );
};



export default ServicesHeader;