import React from "react";
import DSmainmenu from "../DSmainmenu";

const DataProvisioningServices: React.FC = () => {
  return (
    <div className="font-sans text-gray-800">
      {/* Hero Section */}
      <DSmainmenu/>
      <section className="bg-gradient-to-r from-blue-600 to-indigo-500 text-white py-24 px-4 text-center rounded-b-3xl">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">
          Data Provisioning Services
        </h1>
        <p className="max-w-3xl mx-auto text-lg md:text-xl">
          Enable data extraction, replication, mapping, and transformation across your network with Nimble Auity. Make data visible to end-users through a seamless front-end interface.
        </p>
        <a
          href="/contact"
          className="mt-8 inline-block bg-white text-blue-600 font-semibold px-8 py-4 rounded-full shadow-lg hover:bg-gray-100 transition duration-300"
        >
          Get Started
        </a>
      </section>

      {/* Services Section */}
      <section className="py-16 px-4 max-w-7xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Our Data Provisioning Services</h2>
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {[
            {
              title: "Data Licensing Services",
              desc: "Acquire licenses for marketing data, validate and update contact lists every 60 days for reliable and accurate information.",
            },
            {
              title: "Data Segmentation",
              desc: "Segment databases accurately to target relevant audiences and optimize communication efficiency.",
            },
            {
              title: "Data Cleansing",
              desc: "Identify and eliminate inconsistent or inaccurate data using advanced tools and a well-defined cleansing process.",
            },
            {
              title: "Data Appending",
              desc: "Enhance your database with updated and verified information, boosting response rates and conversions.",
            },
            {
              title: "Data Analysis",
              desc: "Perform strategic analysis using descriptive, diagnostic, exploratory, prescriptive, and predictive methods for informed decision-making.",
            },
            {
              title: "Text Analysis",
              desc: "Extract insights from unstructured text, handle ambiguous content, and enable efficient content management and recommendations.",
            },
            {
              title: "Data Monitoring Services",
              desc: "Monitor data in real-time with alerts, dashboards, audit trails, and proactive issue resolution.",
            },
            {
              title: "Data Audit Services",
              desc: "Audit your data thoroughly, create quality scorecards, and define business rules for improved accuracy.",
            },
            {
              title: "Data Strategy",
              desc: "Develop long-term plans for data management, integration, and usability, ensuring structured and actionable data.",
            },
          ].map((service, index) => (
            <div key={index} className="bg-white rounded-xl shadow-lg p-6 hover:shadow-2xl transform hover:-translate-y-2 transition duration-300">
              <h3 className="font-semibold mb-2 text-indigo-600">{service.title}</h3>
              <p className="text-gray-700">{service.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Data Provisioning Process */}
      <section className="py-16 bg-gray-50 px-4 max-w-7xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Our Data Provisioning Process</h2>
        <div className="space-y-8">
          {[
            "Requirement Gathering: Understand the type and volume of structured and unstructured data generated by clients.",
            "Extract: Retrieve data from multiple sources, clean unstructured data, and prepare for transformation.",
            "Transform: Convert and map data to the target system, level semi-structured data, and create relational databases.",
            "Load: Load structured data into target systems, such as data lakes or warehouses, enabling analytics and ML applications.",
          ].map((step, index) => (
            <div key={index} className="bg-white p-6 rounded-xl shadow-md hover:shadow-xl transition duration-300">
              <h3 className="font-semibold mb-2 text-blue-600">{`Step ${index + 1}`}</h3>
              <p className="text-gray-700">{step}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 px-4 max-w-7xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Benefits of Data Provisioning</h2>
        <ul className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 list-disc list-inside text-gray-800">
          {[
            "Save time and reduce operational costs",
            "Improve productivity with advanced technologies",
            "Optimize transparency across users",
            "Ensure data security and privacy",
            "Access expert data provisioning specialists",
            "Easily scalable solutions to meet growing business needs",
            "Ensure regulatory and compliance adherence",
          ].map((benefit, index) => (
            <li key={index} className="bg-white p-4 rounded-xl shadow-md hover:shadow-xl transition duration-300">{benefit}</li>
          ))}
        </ul>
      </section>

      {/* Additional Services */}
      <section className="py-16 bg-gray-50 px-4 max-w-7xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Other Services You Can Benefit From</h2>
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4 text-center">
          {["Data Conversion Services", "Data Analytics Services", "ePUB Solutions", "Optical Character Recognition"].map((service, index) => (
            <div key={index} className="bg-white rounded-xl shadow-md p-6 hover:shadow-xl transition duration-300">
              <p className="text-gray-800 font-medium">{service}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Client Success Stories */}
      <section className="py-16 px-4 max-w-7xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Client Success Stories</h2>
        <div className="grid gap-8 sm:grid-cols-2">
          <div className="bg-white shadow-lg rounded-xl p-6 hover:shadow-2xl transition duration-300">
            <h3 className="font-semibold mb-2">Kansas-based Client</h3>
            <p>Delivered top-quality online data entry services with fast turnaround and reliable support.</p>
          </div>
          <div className="bg-white shadow-lg rounded-xl p-6 hover:shadow-2xl transition duration-300">
            <h3 className="font-semibold mb-2">Tampa-based Legal Client</h3>
            <p>Provided high-quality data extraction services, ensuring accuracy and operational efficiency.</p>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-16 px-4 max-w-4xl mx-auto text-center">
        <h2 className="text-3xl font-bold mb-8">Client Testimonials</h2>
        <blockquote className="bg-white p-8 rounded-xl shadow-lg text-gray-700 italic">
          “We were very satisfied with the quality-of-service Nimble Auity provided. They met our requests with professionalism and flexibility and we look forward to future projects.”
          <cite className="block mt-4 font-semibold not-italic">Spokesperson, Online Health Lessons Company, Canada</cite>
        </blockquote>
      </section>

      {/* Contact CTA */}
      <section className="text-center py-16">
        <a
          href="/contact"
          className="inline-block bg-gradient-to-r from-blue-600 to-indigo-500 text-white font-semibold px-12 py-4 rounded-full shadow-lg hover:opacity-90 transition duration-300"
        >
          Contact Nimble Auity
        </a>
      </section>
    </div>
  );
};

export default DataProvisioningServices;
